export const PILOTOS = [
    {
        "id": 1,
        "codigo": "alexander-albon",
        "nombre": "Alex",
        "apellido": "Albon",
        "nacionalidad": "THA"
    },
    {
        "id": 2,
        "codigo": "carlos-sainz",
        "nombre": "Carlos",
        "apellido": "Sainz",
        "nacionalidad": "ESP",
    },
    {
        "id": 3,
        "codigo": "charles-leclerc",
        "nombre": "Charles",
        "apellido": "Leclerc",
        "nacionalidad": "MON",
    },
    {
        "id": 4,
        "codigo": "esteban-ocon",
        "nombre": "Esteban",
        "apellido": "Ocon",
        "nacionalidad": "FRA",
    },
    {
        "id": 5,
        "codigo": "fernando-alonso",
        "nombre": "Fernando",
        "apellido": "Alonso",
        "nacionalidad": "ESP",
    },
    {
        "id": 6,
        "codigo": "george-russell",
        "nombre": "George",
        "apellido": "Russell",
        "nacionalidad": "GRB",
    },
    {
        "id": 7,
        "codigo": "guanyu-zhou",
        "nombre": "Guanyu",
        "apellido": "Zhou",
        "nacionalidad": "CHN",
    },
    {
        "id": 8,
        "codigo": "kevin-magnussen",
        "nombre": "Kevin",
        "apellido": "Magnussen",
        "nacionalidad": "DNK",
    },
    {
        "id": 9,
        "codigo": "lance-stroll",
        "nombre": "Lance",
        "apellido": "Stroll",
        "nacionalidad": "CAN",
    },
    {
        "id": 10,
        "codigo": "lando-norris",
        "nombre": "Lando",
        "apellido": "Norris",
        "nacionalidad": "GBR",
    },
    {
        "id": 11,
        "codigo": "lewis-hamilton",
        "nombre": "Lewis",
        "apellido": "Hamilton",
        "nacionalidad": "GBR",
    },
    {
        "id": 12,
        "codigo": "logan-sargeant",
        "nombre": "Logan",
        "apellido": "Sargeant",
        "nacionalidad": "USA",
    },
    {
        "id": 13,
        "codigo": "max-verstappen",
        "nombre": "Max",
        "apellido": "Verstappen",
        "nacionalidad": "NLD",
    },
    {
        "id": 14,
        "codigo": "nico-hulkenberg",
        "nombre": "Nico",
        "apellido": "Hulkenberg",
        "nacionalidad": "DEU",
    },
    {
        "id": 15,
        "codigo": "nyck-de-vries",
        "nombre": "Nyck",
        "apellido": "De Vries",
        "nacionalidad": "NLD",
    },
    {
        "id": 16,
        "codigo": "oscar-piastri",
        "nombre": "Oscar",
        "apellido": "Piastri",
        "nacionalidad": "AUS",
    },{
        "id": 17,
        "codigo": "pierre-gasly",
        "nombre": "Pierre",
        "apellido": "Gasly",
        "nacionalidad": "FRA",
    },
    {
        "id": 18,
        "codigo": "sergio-perez",
        "nombre": "Sergio",
        "apellido": "Perez",
        "nacionalidad": "MEX",
    },
    {
        "id": 19,
        "codigo": "valtteri-bottas",
        "nombre": "Valtteri",
        "apellido": "Bottas",
        "nacionalidad": "FIN",
    },
    {
        "id": 20,
        "codigo": "yuki-tsunoda",
        "nombre": "Yuki",
        "apellido": "Tsunoda",
        "nacionalidad": "JPN",
    }
]
